### PR TITLE
Fix wizard event

### PR DESCRIPTION
**Pull request by Ajver**
I fixed bug with clicking on wizard event. The problem was in stats (currently we are keeping elf stats in ElfStats singleton, but in Wizard.gd was getted from elf.stats). Also I changed version number to 0.14.3

### CODE REVIEW

**Comment by B0ZIA** [comment]
Ok, all is well

**Comment by B0ZIA** [comment]
but main menu is not well scaled

**Comment by B0ZIA** [comment]
besides, you did a nice scroll about us in the main menu

**Comment by Ajver** [comment]
I tried to fix scale bug before creating this PR but there was problems and versions didn't merged well, so I'll fix this after merge. Thanx for review!

**Pull request merged**
